### ISSUE TITLE
feat: pass handlers in the config

### ISSUE THREAD

**Issue by aarondill** [MarcHamamji/runner.nvim#20]
something like
```lua
require('runner.nvim').setup({
  handlers = {
    java = -- your handler here
  }
})
```
which would be merged with the default handlers

**Comment by MarcHamamji** [comment]
Hello,

This is a great idea, I'm going to work on it this week (If you would like to, don't hesitate).
I also have to figure out how to "join" the user-provided handlers with the default ones using the `choice` helper since handlers are just functions.

Thanks for the suggestion

**Comment by aarondill** [comment]
I was thinking a simple implementation which overrides the defaults (sorry for the bad wording).
It just simplifies the process of configuring, consolidating the handlers into `setup()` rather than requiring separate configuration.
```lua
for filetype, handler in pairs(config.handlers) do
   set_handler(filetype, handler)
end
```

**Comment by MarcHamamji** [comment]
The problem of using the `set_handler` function to set the user-provided handlers is that it overwrites the default handlers, I think it's a better idea to find a way to add handlers to default ones.

**Comment by MarcHamamji** [comment]
Sorry for taking so long to do it although it's a simple change, but I have added the option to pass the handlers to the `setup` function in 16a2c9c.
It still overwrites the old handers, but eventually I will change the whole way I store the handlers. I would use tables instead of functions for handlers to make it much more modular.

Thanks for the suggestion
